apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: udagram-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80  
  
