apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverse-proxy
  name: udagram-reverse-proxy
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: api
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-reverse-proxy
  type: LoadBalancer